require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-discourse

AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*
    - db/**/*
    - vendor/**/*

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Rails/I18nLocaleTexts:
  Enabled: false

RSpec/Capybara/FeatureMethods:
  EnabledMethods:
    - feature
    - scenario

RSpec/ExampleLength:
  Enabled: false