name: action-test
on: [push]
jobs:  
  ci:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432
      RAILS_ENV: test
    services:
     postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports: 
           - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run quality
        run: bin/quality

      - name: Setup database
        run: bin/rails db:setup
    
      - name: Check functional test
        run: bin/test